# Generated by Django 5.0 on 2023-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="Name Surname"),
                ),
                ("emalil", models.CharField(max_length=50, verbose_name="E-mail")),
                (
                    "message",
                    models.TextField(max_length=250, verbose_name="Your Message"),
                ),
            ],
        ),
    ]
