# Generated by Django 5.0 on 2023-12-22 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactformmodel",
            name="emalil",
        ),
    ]
